name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'requirements.txt'
      - 'Dockerfile'
      - '*.py'
      - 'templates/**'
      - 'static/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/youth-secure-checkin:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/youth-secure-checkin:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/youth-secure-checkin:buildcache,mode=max
      
      - name: Build and push demo
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/youth-secure-checkin:demo
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/youth-secure-checkin:buildcache
